### ISSUE TITLE
Create Chicago CTA Data API Extraction Code

### ISSUE THREAD

**Issue by jimenasalinas** [uchicago-capp-30320/RouteRangers#10]

**Comment by meganhmoore** [comment]
at end of ticket create new issue for GTFS if needed and communicate

**Comment by mbjackson-capp** [comment]
GTFS static/scheduled feed is pretty easily obtained for all three cities without needing API key. Putting off GTFS live feed extraction for now. 
Checklist for handling GTFS feeds in advance of 4/16 meeting:
- [ ] Download static feed to local directory to start, saving routes for repeat download if necessary (New York MTA train, New York MTA bus, Chicago CTA train, Chicago CTA bus, Chicago Metra, Portland TriMet)
  - [ ] note: stop_times.txt can be larger than GitHub max file size so should be kept locally or obtained only via API request directly into memory
- [ ] Write code (i.e. use existent library code) to load a particular feed into memory as geoPandas dataframes or similar manipulable table
    - [ ] create primary keys of city_agency_mode
- [ ] Write test for load-in process
- [ ] Write code (i.e. use existent library code)to visualize feed routes (ideally color coded for train lines)
- [ ] save shapes.txt as geometry line objects

**Comment by mbjackson-capp** [comment]
Resolved by later pull requests; deleting branch since no longer needed
