### ISSUE TITLE
Survey Dashboard: Map with Responses (MVP)

### ISSUE THREAD

**Issue by lisette-solis** [uchicago-capp-30320/RouteRangers#126]
As a policy maker, I want to understand patterns in the routes survey respondents reported. 

**Acceptance criteria**

Map with similar functionality as map on policy maker dashboard that displays the start and end points from route_rangers_api_plannedroute

**Comment by mbjackson-capp** [comment]
As discussed at Monday AM standup, I think it's best for survey respondent routes to go on the same map as everything else; the layer control will let policymaker show or hide them as desired

**Comment by mbjackson-capp** [comment]
If plan is to have map without these on dashboard page and map with these on survey response page, we can reuse `map.js` for both, passing an extra parameter boolean into the main function: `displayUserDrawnRoutes=False` for dashboard, `=True` for survey response page.

Then put code to add user drawn routes to map in an if block

**Comment by mbjackson-capp** [comment]
Resolved by #117. We settled on having survey results page link to the existing map on Dashboard, and putting in user-drawn routes/endpoints as a togglable layer on that existing map
