### ISSUE TITLE
Survey Dashboard: Bar Charts

### ISSUE THREAD

**Issue by lisette-solis** [uchicago-capp-30320/RouteRangers#127]
As a policy maker, I want to understand trends in survey responses. 

**Acceptance criteria**
Filterable charts for the key survey questions. See prototype for details

![Image](https://github.com/uchicago-capp-30320/RouteRangers/assets/111702116/e1dd9f27-964e-4766-9687-4e12987601b6)

**Comment by lisette-solis** [comment]
@benjaleivas, @jimenasalinas, or I can pick this up depending on availability.

**Comment by kdumais111** [comment]
@lisette-solis I can do this because it branches well off of what I have already been working on

**Comment by lisette-solis** [comment]
Perf, thanks Katherine!
