### ISSUE TITLE
Prototypes

### ISSUE THREAD

**Issue by lisette-solis** [uchicago-capp-30320/RouteRangers#14]
A prototype of the web app will be useful for getting the team aligned on the MVP, user testing, and creating CSS elements. 
- general page skeleton
- main page city selection
- policy/community toggle 
- map component for community members
- form design & data

Acceptance criteria: 
- Prototype in [Figma ](https://www.figma.com/file/bXKQi5P1RpGKSb1Ao6w0V5/Community-Transit-Tool?type=design&node-id=0-1&mode=design&t=Hq9pcP90gVrj9UDK-0)
- Add write up of prototypes to Git

**Comment by meganhmoore** [comment]
Create `design` or `documentation` folder and markdown file with prototypes 
Link file to Readme so it is easy to find.
