### ISSUE TITLE
Load Geo Tables from GTFS

### ISSUE THREAD

**Issue by meganhmoore** [uchicago-capp-30320/RouteRangers#30]
Extend ingestion scripts to pull relevant transit data and load associated tables:

- [x] Bus & Subway stop points for Chicago, NY, Portland
- [x] Bus & Subway routes (question about format to get these done) Chicago, NY, Portland
- [x] Using the django model objects that were created to create new rows, reference the django management to enable ingestion scripts to use models
- [x] call each city's API and load it into the bus table, subway table
- [ ] write django test to confirm

**Comment by meganhmoore** [comment]
Reach out to @JPMartinezClaeys and @meganhmoore if you want to pair program an example

**Comment by mbjackson-capp** [comment]
@meganhmoore @JPMartinezClaeys Everything here is resolved except fixing the tests to run via `pytest-django` -- should we retool this issue to be about that or start a new one?

**Comment by mbjackson-capp** [comment]
I think we can close this per Lisette's call to close unneeded issues
