### ISSUE TITLE
Create a leaflet map

### ISSUE THREAD

**Issue by lisette-solis** [uchicago-capp-30320/RouteRangers#31]
**Goals**

- Need to get familiar with leaflet and relevant packages like folium. 
- Need to get better understanding of backend needs for leaflet. 

**Acceptance criteria:** 
Create a basic map in leaflet that allows us to: 

- Zoom in/zoom out
- Search for places on the map
- Select a layer

**Comment by mbjackson-capp** [comment]
Resolved by a lot of other issues and PRs already
