### ISSUE TITLE
Create database

### ISSUE THREAD

**Issue by lisette-solis** [uchicago-capp-30320/RouteRangers#5]
Need a central database that team members can read data from and write data to
- Set-up database in PostgreSQL
- Give team members edit permissions

**Comment by meganhmoore** [comment]
Need to figure out where prod db is going to live, but probably for now we can spin up a postgres db locally unless cloud folks know of a better way to do things. 

This may be a starting point for the local approach: https://github.com/meganhmoore/CodeForAmerica/tree/main/db (JP should have access, lmk if I should add others)

**Comment by meganhmoore** [comment]
Turk will set up postgres shared db
