### ISSUE TITLE
Policy Maker Heatmaps

### ISSUE THREAD

**Issue by lisette-solis** [uchicago-capp-30320/RouteRangers#85]
As a policy maker, I want to be able to see trends in demographic data as they relate to transit. 

**Acceptance criteria**
Heat map (aka [choropleth map](https://leafletjs.com/examples/choropleth/)) which shows spatial trends in census data with the following functionality: 

- [ ] Legend
- [ ] Search for specific neighborhoods (see how this is being done in the other map)
- [ ] Ability to toggle between different demographic variables

**Comment by lisette-solis** [comment]
@kdumais111 and @mbjackson-capp and @benjaleivas, I think whoever is done first with their other work can pick this up.

**Comment by meganhmoore** [comment]
show commute time choropleth by census tract
